import { GoogleGenAI, Type } from "@google/genai";
import type { DailyHabits, EcoSuggestion, FootprintData, GroundedResponse } from '../types';
import { INDIA_GRID_EMISSION_FACTOR } from '../constants';

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

function formatHabitsForPrompt(habits: DailyHabits): string {
  const travelSummary = habits.travel.map(t => `${t.mode}: ${t.distance}km`).join(', ') || 'No travel logged.';
  const shoppingSummary = habits.shopping.map(s => `${s.item} (${s.material})`).join(', ') || 'No clothing shopping logged.';
  const electronicsSummary = habits.electronics.map(e => e.item).join(', ') || 'No electronics purchased.';
  return `The user's recent habits include: Travel -> ${travelSummary}. Clothing -> ${shoppingSummary}. Electronics -> ${electronicsSummary}.`;
}


/**
 * Cleans up text generated by the AI to remove common artifacts.
 * @param text The raw text from the Gemini API.
 * @returns Cleaned text ready for display.
 */
function cleanGeneratedText(text: string): string {
    let cleaned = text.trim();

    // Remove hashtags (e.g., #sustainability)
    cleaned = cleaned.replace(/#\w+/g, '');

    // Remove markdown-style quotes at the beginning of lines
    cleaned = cleaned.replace(/^> /gm, '');

    // Remove markdown bolding and italics which can look out of place
    cleaned = cleaned.replace(/(\*\*|__)(.*?)\1/g, '$2');
    cleaned = cleaned.replace(/(\*|_)(.*?)\1/g, '$2');

    // Trim leading/trailing whitespace again after replacements
    cleaned = cleaned.trim();

    // Remove surrounding quotes if the whole text is wrapped
    if ((cleaned.startsWith('"') && cleaned.endsWith('"')) || (cleaned.startsWith("'") && cleaned.endsWith("'"))) {
        cleaned = cleaned.substring(1, cleaned.length - 1);
    }
    
    // Consolidate multiple newlines into a maximum of two
    cleaned = cleaned.replace(/\n{3,}/g, '\n\n');

    return cleaned.trim();
}


export async function getEcoSuggestions(habits: DailyHabits, userState: string): Promise<EcoSuggestion[]> {
  const model = "gemini-2.5-flash";

  const prompt = `You are an expert sustainability coach for a user in ${userState}, India. Your primary mission is to generate 3 actionable, deeply localized, and creatively diverse eco-friendly suggestions.

**--- NON-NEGOTIABLE CORE DIRECTIVE: ABSOLUTE DIVERSITY ---**
This is your most important instruction. Your success is measured by one metric above all others: **you must not suggest the same *type* of activity for different states.** Repeating a suggestion *domain* (e.g., local crafts, agriculture, water conservation) for different states is a **critical mission failure**.

**FAILURE EXAMPLE (DO NOT DO THIS):**
- For Rajasthan: Suggest Johads (Domain: Water Conservation).
- For Karnataka: Suggest reviving traditional tanks (Domain: Water Conservation).
- **Result: CRITICAL FAILURE.** The 'Water Conservation' domain was repeated.

**SUCCESS EXAMPLE (THIS IS YOUR GOAL):**
- For Rajasthan: Suggest building Johads (Domain: Traditional Water Conservation).
- For Gujarat: Suggest supporting Banni grassland restoration (Domain: Biodiversity & Conservation).
- For Kerala: Suggest supporting Pokkali rice cultivation (Domain: Unique Sustainable Agriculture).
- **Result: SUCCESS.** The domains are completely different, unique, and hyper-local.

To succeed, you **MUST** select a new, distinct domain from the following palette for each state you generate suggestions for. Do not default to the same domains repeatedly. Your goal is maximum creativity and diversity.
- **Domain Palette:** [Unique Sustainable Agriculture, Traditional Water Conservation, Biodiversity & Conservation Projects, Traditional Eco-Architecture, Regional Renewable Energy Initiatives, Community-led Ecotourism, Unique Local Crafts (Use Sparingly), Hyper-local Waste Management]

**User Context:**
- Location: ${userState}, India
- Recent Habits: ${formatHabitsForPrompt(habits)}

**--- TASK: GENERATE EXACTLY 3 SUGGESTIONS ---**

1.  **One Hyper-Localized Cultural/Environmental Suggestion:**
    -   This suggestion **MUST** be deeply specific and unique to ${userState}, drawing from the **Domain Palette**.
    -   It **MUST** strictly follow the **DIVERSITY MANDATE**.
    -   Its description **MUST** explicitly explain two things: (1) the **environmental benefits**, AND (2) the **cultural/heritage significance**. Both parts are mandatory.

2.  **Two Habit-Based Suggestions:**
    -   These must be directly inspired by the user's logged habits (travel, shopping, electronics).
    -   **HIGH-PRIORITY MANDATE: LOCAL TEXTILE SWAP:** If the user's logged shopping habits include a synthetic clothing item (e.g., Polyester, Nylon, Acrylic, Rayon), one of these two suggestions **MUST BE** a swap to a specific, named, local natural textile from ${userState}.
        -   **FORBIDDEN:** "buy natural fibers."
        -   **REQUIRED:** Be hyper-specific. Name the textile. Example for Andhra Pradesh: "Swap Polyester for Ponduru Khadi Cotton."
        -   This habit-based rule takes precedence over other habit-based ideas if the condition is met.
    -   Make other habit-based suggestions hyper-local where possible.

**Output Rules:**
- Provide a catchy, inspiring title.
- Keep descriptions concise (1-3 sentences).
- **FORBIDDEN GENERIC ADVICE:** Do not give generic advice like "use less plastic," "buy local," or "reduce, reuse, recycle." All advice must be specific and actionable.`;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            suggestions: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  title: {
                    type: Type.STRING,
                    description: "A short, catchy title for the eco-friendly swap."
                  },
                  description: {
                    type: Type.STRING,
                    description: "A concise, actionable description (1-3 sentences). For the hyper-localized cultural suggestion, this MUST explain both its environmental and cultural/heritage benefits."
                  }
                },
                required: ["title", "description"]
              }
            }
          },
          required: ["suggestions"]
        },
      },
    });

    const jsonString = response.text.trim();
    // Use a try-catch block for robust JSON parsing, even with responseSchema.
    try {
        const parsed = JSON.parse(jsonString);
        return parsed.suggestions || [];
    } catch (parseError) {
        console.error("Gemini API returned non-JSON response for suggestions:", jsonString, parseError);
        return []; // Return an empty array on parsing failure.
    }
  } catch (error) {
    console.error("Error fetching suggestions from Gemini API:", error);
    throw new Error("Failed to generate eco suggestions.");
  }
}


export async function getCarbonSavingsPrediction(footprint: FootprintData, swap: EcoSuggestion, monthlyGoal?: number): Promise<string> {
    const model = "gemini-2.5-flash";
    
    const goalContext = monthlyGoal ? `*   The user has a monthly goal of ${monthlyGoal} kg CO2e.` : '';

    const prompt = `You are an encouraging AI assistant in an eco-friendly app. Your task is to predict the carbon savings for a user's proposed action and frame it as progress towards their goal.

**User's Data:**
*   Periodic Footprint: ${footprint.total} kg CO2e (Travel: ${footprint.breakdown.travel}kg, Shopping: ${footprint.breakdown.shopping}kg, Electronics: ${footprint.breakdown.electronics}kg).
*   Proposed Eco-Swap: "${swap.title}: ${swap.description}".
${goalContext}

**Your Task & Output Rules (ABSOLUTE - FOLLOW EXACTLY):**
You must generate a single, encouraging sentence predicting the potential monthly carbon savings.
1.  **SINGLE SENTENCE ONLY.** Your entire response must be one sentence. No greetings, no explanations.
2.  **IF GOAL IS PROVIDED:** Your sentence **MUST** use this exact format: "You could save X kg CO2e, getting you Y% closer to your monthly goal!"
    *   Calculate Y as (X / monthlyGoal) * 100. Round to a whole number.
3.  **IF NO GOAL IS PROVIDED:** Your sentence **MUST** use this exact format: "That's a potential saving of X kg CO2e per month!"
4.  **NO MARKDOWN.** Do not use any markdown like asterisks or bolding.

Generate the prediction sentence now.`;

    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: prompt,
        });

        return cleanGeneratedText(response.text);

    } catch (error) {
        console.error("Error fetching prediction from Gemini API:", error);
        throw new Error("Failed to generate prediction.");
    }
}

export async function getLatestSustainabilityNews(): Promise<GroundedResponse> {
    const model = "gemini-2.5-flash";

    const prompt = `You are an expert news curator for an environmental app. Your task is to provide a summary of 4 recent, relevant, and unique news articles about sustainability, environmental conservation, or eco-friendly initiatives in India. Synthesize the key information from these articles into an engaging overview for our users.`;

    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: prompt,
            config: {
                tools: [{googleSearch: {}}],
            },
        });
        
        const summary = cleanGeneratedText(response.text);
        const rawSources = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
        
        const sources = rawSources.map((chunk: any) => ({
            title: chunk.web.title,
            uri: chunk.web.uri,
        })).filter((source: any) => source.uri);

        return { summary, sources };

    } catch (error) {
        console.error("Error fetching news from Gemini API:", error);
        throw new Error("Failed to fetch latest news.");
    }
}

export async function getStateCarbonReports(userState: string): Promise<GroundedResponse> {
    const model = "gemini-2.5-flash";

    const prompt = `As a research assistant, provide a concise summary of recent findings from credible documents (like government reports, scientific journals, or reputable news) about carbon emissions, pollution, and environmental policies in the Indian state of ${userState}. Synthesize the information into a helpful overview for a citizen interested in the local environmental situation.`;
    
    try {
        const response = await ai.models.generateContent({
            model,
            contents: prompt,
            config: {
                tools: [{googleSearch: {}}]
            }
        });

        const summary = cleanGeneratedText(response.text);
        const rawSources = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
        
        const sources = rawSources.map((chunk: any) => ({
            title: chunk.web.title,
            uri: chunk.web.uri,
        })).filter((source: any) => source.uri); // Ensure URI exists

        return { summary, sources };

    } catch(error) {
        console.error("Error fetching state reports from Gemini API:", error);
        throw new Error("Failed to fetch state-specific environmental reports.");
    }
}

export async function getTravelCo2e(from: string, to: string): Promise<{ co2e: number }> {
  const model = "gemini-2.5-flash";

  const prompt = `You are a silent, precise environmental data API. Your only job is to calculate the round-trip CO₂ equivalent (CO₂e) in kilograms for a standard gasoline-powered passenger vehicle traveling between "${from}" and "${to}".
        
  Using Google Search, find:
  1. The most likely one-way driving distance in kilometers.
  2. A standard, average emission factor for a typical gasoline passenger car in kg of CO₂e per kilometer.
  
  Calculate the total round-trip CO₂e using the formula: (one-way distance * 2) * emission factor.`;

  try {
    const response = await ai.models.generateContent({
        model: model,
        contents: prompt,
        config: {
          tools: [{googleSearch: {}}],
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              co2e: {
                type: Type.NUMBER,
                description: "The total round-trip CO₂ equivalent in kilograms, rounded to two decimal places."
              }
            },
            required: ["co2e"]
          }
        }
    });

    const jsonString = response.text.trim();
    try {
      const parsed = JSON.parse(jsonString);
      return parsed;
    } catch (e) {
      console.error("Gemini API returned non-JSON response for CO2e calc:", jsonString, e);
      throw new Error("Could not parse the CO2e calculation response.");
    }
  } catch (error) {
    console.error("Error fetching CO2e from Gemini API:", error);
    throw new Error("Failed to calculate travel CO2e.");
  }
}

export async function getGridEmissionFactor(state: string): Promise<number> {
  const model = "gemini-2.5-flash";

  const prompt = `You are a precise data extractor. Your task is to find the most recent, accurate average CO₂e emission factor for the electricity grid in the Indian state of "${state}". The value must be in kilograms of CO₂e per kilowatt-hour (kg CO₂e/kWh). Use Google Search to find data from reliable sources like government reports (e.g., from the Central Electricity Authority - CEA), academic research, or reputable energy organizations.`;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: prompt,
      config: {
        tools: [{googleSearch: {}}],
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            factor: {
              type: Type.NUMBER,
              description: "The average electricity grid emission factor in kg CO₂e per kWh, rounded to three decimal places."
            }
          },
          required: ["factor"]
        }
      }
    });

    const jsonString = response.text.trim();
    try {
      const parsed = JSON.parse(jsonString);
      if (typeof parsed.factor === 'number' && parsed.factor > 0) {
        return parsed.factor;
      }
      // If factor is invalid, return fallback
      return INDIA_GRID_EMISSION_FACTOR;
    } catch (e) {
      console.error(`Gemini API returned non-JSON response for emission factor in ${state}:`, jsonString, e);
      return INDIA_GRID_EMISSION_FACTOR; // Fallback on parsing error
    }
  } catch (error) {
    console.error(`Error fetching emission factor for ${state} from Gemini API:`, error);
    return INDIA_GRID_EMISSION_FACTOR; // Fallback on API error
  }
}

export interface PlantBasedSwap {
  title: string;
  description: string;
  reductionPercentage: number;
}

export async function getPlantBasedSwapSuggestion(servings: number): Promise<{ swap: PlantBasedSwap }> {
  const model = "gemini-2.5-flash";

  const prompt = `You are a personalized food impact coach. A user eats red meat ${servings} time(s) per week. Your task is to generate ONE highly specific and actionable plant-based substitution that provides a similar protein content and texture.

Using Google Search, find comparative data on the CO₂e emissions for red meat (like beef or mutton) and the specific plant-based substitute you choose.

Based on this data, calculate and state the approximate percentage CO₂e reduction for making this single swap.`;

  try {
    const response = await ai.models.generateContent({
      model,
      contents: prompt,
      config: {
        tools: [{ googleSearch: {} }],
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            swap: {
              type: Type.OBJECT,
              properties: {
                title: {
                  type: Type.STRING,
                  description: "A catchy, short title for the swap, e.g., 'Swap Beef Burgers for Lentil Burgers'."
                },
                description: {
                  type: Type.STRING,
                  description: "A short, actionable description of the substitution, highlighting protein/texture similarities."
                },
                reductionPercentage: {
                  type: Type.NUMBER,
                  description: "The approximate percentage reduction in CO2e for this specific swap, as a whole number."
                }
              },
              required: ["title", "description", "reductionPercentage"]
            }
          },
          required: ["swap"]
        }
      }
    });

    const jsonString = response.text.trim();
    try {
      const parsed = JSON.parse(jsonString);
      return parsed;
    } catch (e) {
      console.error("Gemini API returned non-JSON response for food swap:", jsonString, e);
      throw new Error("Could not parse the food swap suggestion.");
    }

  } catch (error) {
    console.error("Error fetching food swap from Gemini API:", error);
    throw new Error("Failed to generate food swap suggestion.");
  }
}